### PR TITLE
Potential improvement, drop classNames dependency

### PR DESCRIPTION
**Pull request by earthlingdavey**
Hi I think there's a potential here to drop the classNames dependency. 

Here I've replaced it with:
- add classes to an array (some will be false if conditions aren't met)
- filter for truthy values
- join array elements with a space

I 100% don't mind if you don't merge. I have done this work anyway for my own project.

Cheers, Davey

### CODE REVIEW

**Comment by Stanko** [comment]
Hi @EarthlingDavey,
Thank you for the contribution! ATM I have some personal stuff to take care of, but I will probably merge this in the next 7-10 days. I'm always interested in dropping dependencies 🙈 

Cheers!

**Comment by earthlingdavey** [comment]
Awesome, and thanks for the project BTW. I just dropped it into my app and it works 100% - will reccomend :)

**Comment by Stanko** [comment]
Thanks again, released in 3.1.0 🎉

**Comment by earthlingdavey** [comment]
No problem bud 🎉✌️

**Pull request merged**
