### PR TITLE
Make this package work with tools that use ESM

### PR DESCRIPTION
**Pull request by sdegutis**
In particular, https://www.pika.dev/search?q=react-animate-height/

See https://www.pika.dev/blog/pika-web-a-future-without-webpack/ for more details

### CODE REVIEW

**Comment by Stanko** [comment]
Thank you, I'll release it to npm right away!

**Comment by sdegutis** [comment]
Great thanks @Stanko 👍

**Comment by Stanko** [comment]
react-animate-height@2.0.10 is released 🎉

**Comment by sdegutis** [comment]
Hmm I wonder why https://www.pika.dev/search?q=react-animate-height/ isn't updated to show that your library works great now. I bet it has a cache, I wonder how to force it as a user for a specific package, if possible... @FredKSchott, any ideas?

**Comment by FredKSchott** [comment]
We fetch from Cloudflare's mirror of npm (allows CORs requests), but it looks like they're just doing some caching on the response. I'd just give it a second

**Comment by FredKSchott** [comment]
Following up: looks the npm cache has been updated, but one of its dependencies is broken: https://unpkg.com/react-animate-height@2.0.10/ (source/index.js doesn't actually exist in the package)

**Comment by Stanko** [comment]
Should be fine now. `source` folder was in `.npmignore`

https://unpkg.com/react-animate-height@2.0.11/source/

Cheers!

**Comment by sdegutis** [comment]
Oh yeah I didn't consider that Pika might not know what to do with the JSX during Rollup phase... Hmm... @FredKSchott thoughts?

**Comment by FredKSchott** [comment]
Yea, you shouldn’t publish JSX to npm (not standard JS, unclear what framework to connect it to, etc). Sounds like you’ll need to still build your ESM distribution, check out @pika/pack or microbundle

**Comment by Stanko** [comment]
Correct me I'm wrong, but I think confusion was created by this PR. It changed `package.json` and added
```
"module": "src/index.js"
```

instead of transpiled version
```
"module": "lib/index.js"
```

Especially as I don't release `src` folder to npm.

You can check file here:
https://unpkg.com/react-animate-height@2.0.13/lib/index.js

Is that solution to this one?

@FredKSchott @sdegutis

**Comment by sdegutis** [comment]
That sounds right to me. Although I don't know of the CJS format will be compatible with the current version of Pika/{CDN,web}, it might require pikapkg/web#62 first.

**Pull request merged**
