### PR TITLE
Modernization Updates

### PR DESCRIPTION
**Pull request by darthtrevino**
Hey @Stanko  - there's some moving parts to this PR, but basically we're running into issues where the library output isn't being handled in some builds because it's not shipped with proper ESM. This PR updates the following:

* Ships the library with ESM output
* Uses TypeScript source. Transpilation is done with `swc` and type-generation is done with `typescript`
* Updates the Webpack build with a more modern configuration; uses `swc-loader` for transpiling source 
* Remove babel
* Use `prettier` for formatting source; disable all formatting-based `eslint rules`
* Add a GitHub Action for CI verification
* Use yarn v3 for enhanced TS + Semver support. It's in node-modules mode, so you don't have to worry about PnP issues.

### CODE REVIEW

**Comment by Stanko** [comment]
Woah, this is huge, honestly, AnimateHeight is ready to be modernized! Thank you so much for putting the effort in.

I just skimmed the changes, and they look great. I'm not familiar with all of the tooling, so please allow me some more time to review.

What do you think of completely removing webpack for parcel (unrelated to this PR)?

**Comment by darthtrevino** [comment]
Honestly, if I were making a static docsite from scratch I'd probably use Vite

**Comment by Stanko** [comment]
Sorry I haven't done anything about this PR. Honestly, I'm a little burned out, and can't make myself go through PRs. That said, this library is begging to be rewritten to hooks (and typescript), so I will definitely use your work once I start doing that. Thank you and sorry again!

**Comment by Stanko** [comment]
I actually made myself rewrite it to hooks and typescript:
https://github.com/Stanko/react-animate-height/compare/v3?expand=1

It exports both esm and cjs module, and I tried to keep dependencies at the minimum. 

Let me know what you think.

**Comment by darthtrevino** [comment]
That's perfect, I think that route  is a more comprehensive update

**Pull request closed without merging**
